include:
  # - board: nice_nano_v2
  #   shield: tester_pro_micro

  # Hillside
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: hillside46_right
  - board: nice_nano_v2
    shield: hillside46_left
  - board: seeeduino_xiao_ble
    shield: hillside46_dongle dongle_screen
  - board: nice_nano_v2
    shield: hillside46_dongle

  # Kyria
  - board: nice_nano_v2
    shield: kyria_rev3_left
  - board: nice_nano_v2
    shield: kyria_rev3_right
  - board: seeeduino_xiao_ble
    shield: kyria_rev3_dongle
