---
include:

  - board: nice_nano_v2
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset

  # - board: nice_nano_v2
  #   shield: tester_pro_micro
    
  # - board: nice_nano_v2
  #   shield: kyria_rev3_left

  # - board: nice_nano_v2
  #   shield: kyria_rev3_right
    
  # - board: nice_nano_v2
  #   shield: hillside46_left
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
    
  - board: nice_nano_v2
    shield: hillside46_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano_v2
    shield: hillside46_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # - board: seeeduino_xiao_ble
  #   shield: hillside46_dongle prospector_adapter
  
  - board: seeeduino_xiao_ble
    shield: hillside46_dongle dongle_screen