include:
  # - board: nice_nano_v2
  #   shield: tester_pro_micro
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: hillside46_right
  - board: nice_nano_v2
    shield: hillside46_left
  - board: seeeduino_xiao_ble
    shield: hillside46_dongle dongle_screen
  - board: nice_nano_v2
    shield: hillside46_dongle
