services:
  builder:
    image: zmkfirmware/zmk-dev-arm:stable
    volumes:
      - ../:/zmk-config:ro
      - ../firmwares:/firmwares:rw
    working_dir: /zmk-config
    environment:
      - KEYBOARD
    entrypoint: []
    command:
      - bash
      - ./local-build/build_setup.sh
    tty: true
    stdin_open: true
