name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    steps:
  
    - name: Get current date and time
      run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
      shell: bash

    - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
      with:
        archive_name: zmk-firmware-${{ env.BUILD_DATE }}

