name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:

  set-env:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.date.outputs.build_date }}
    steps:
      - id: date
        run: echo "build_date=$(date -u +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

  build:
    needs: set-env
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      archive_name: zmk-firmware-${{ needs.set-env.outputs.build_date }}

